/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tianfei_myjni_2_MainActivity */

#ifndef _Included_com_example_tianfei_myjni_2_MainActivity
#define _Included_com_example_tianfei_myjni_2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_example_tianfei_myjni_12_MainActivity_displayJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
